name: hotel_test_e_m
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  retrofit: ">=4.0.0 <5.0.0"
  json_annotation: ^4.8.1
  dio: ^5.4.0
  provider: ^6.1.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ">=2.3.0 <4.0.0"
  flutter_lints: ^2.0.0
  retrofit_generator: ">=7.0.0 <8.0.0"
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true
